spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/buffer
    username: buffer
    password: iamworking
    initialization-mode: always
    schema: classpath:db/schema.sql

  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
