spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/buffer
    username: buffer
    password: iamworking

  sql:
    init:
      mode: always
      data-locations: classpath:db/data.sql

  jpa:
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        #show_sql: true
        #format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
