spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/buffer
    username: buffer
    password: iamworking

  sql:
    init:
      mode: always
      data-locations: classpath:db/data.sql
      schema-locations: classpath:db/schema.sql

  jpa:
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
