spring:
  sql:
    init:
      data-locations:
  jpa:
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
